import { defineConfig } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
    output: 'server',
    adapter: cloudflare(),
    integrations: [tailwind()],
    vite: {
        ssr: {
            external: [
                'node:buffer',
                'node:crypto',
                'node:os',
                'node:process',
                'node:url',
                'node:net',
                'node:dns',
                'node:child_process',
                'node:assert',
                'node:fs',
                'node:path',
                'node:util',
                'node:dgram',
                'node:events',
                'node:tls',
                'node:http',
                'node:https',
                'node:stream',
                'net',
                'http2',
                'stream',
                'zlib',
                'tls',
                'events',
                'os',
                'crypto',
                'buffer',
                'process',
                'url',
                'dns',
                'child_process',
                'assert',
                'fs',
                'path',
                'util',
                'dgram',
                'events',
                'http',
                'https',
                'string_decoder'
            ],
        },
    },
});